### PR TITLE
Fix remove bus watch leak

### LINKED ISSUE #107: Bus.AddWatch pointer leakage
Another leakage:

mem profiling shows these huge-leaking places:
```
1: 3620864 [1: 3620864] @ 0x42fead 0x43166f 0x433399 0x6bb4c5 0x6d0ebf 0x6e4231 0x6e415e 0x4938c1
#       0x6bb4c4        github.com/mattn/go-pointer.Save+0x84                   /gopath/pkg/mod/github.com/mattn/go-pointer@v0.0.1/pointer.go:30
#       0x6d0ebe        github.com/go-gst/go-gst/gst.(*Bus).AddWatch+0x1e       /gopath/src/my/go-gst_upstream/gst/gst_bus.go:131
#       0x6e4230        main.test_func+0x50                                     /app/test1/test1.go:74
#       0x6e415d        main.bench+0x1d                                         /app/test1/test1.go:53

...

0: 0 [1: 229376] @ 0x42fead 0x43166f 0x433399 0x6bb4c5 0x6d0ebf 0x6e4231 0x6e415e 0x4938c1
#       0x6bb4c4        github.com/mattn/go-pointer.Save+0x84                   /gopath/pkg/mod/github.com/mattn/go-pointer@v0.0.1/pointer.go:30
#       0x6d0ebe        github.com/go-gst/go-gst/gst.(*Bus).AddWatch+0x1e       /gopath/src/my/go-gst_upstream/gst/gst_bus.go:131
#       0x6e4230        main.test_func+0x50                                     /app/test1/test1.go:74
#       0x6e415d        main.bench+0x1d                                         /app/test1/test1.go:53

...

0: 0 [1: 1810432] @ 0x42fead 0x43166f 0x433399 0x6bb4c5 0x6d0ebf 0x6e4231 0x6e415e 0x4938c1
#       0x6bb4c4        github.com/mattn/go-pointer.Save+0x84                   /gopath/pkg/mod/github.com/mattn/go-pointer@v0.0.1/pointer.go:30
#       0x6d0ebe        github.com/go-gst/go-gst/gst.(*Bus).AddWatch+0x1e       /gopath/src/my/go-gst_upstream/gst/gst_bus.go:131
#       0x6e4230        main.test_func+0x50                                     /app/test1/test1.go:74
#       0x6e415d        main.bench+0x1d                                         /app/test1/test1.go:53

...

0: 0 [1: 909312] @ 0x42fead 0x43166f 0x433399 0x6bb4c5 0x6d0ebf 0x6e4231 0x6e415e 0x4938c1
#       0x6bb4c4        github.com/mattn/go-pointer.Save+0x84                   /gopath/pkg/mod/github.com/mattn/go-pointer@v0.0.1/pointer.go:30
#       0x6d0ebe        github.com/go-gst/go-gst/gst.(*Bus).AddWatch+0x1e       /gopath/src/my/go-gst_upstream/gst/gst_bus.go:131
#       0x6e4230        main.test_func+0x50                                     /app/test1/test1.go:74
#       0x6e415d        main.bench+0x1d                                         /app/test1/test1.go:53
```

All other places - are just small/ok.

So, obviously that in:
```
func (b *Bus) AddWatch(busFunc BusWatchFunc) bool {
	fPtr := gopointer.Save(busFunc)
	return gobool(
		C.int(C.gst_bus_add_watch(
			b.Instance(),
			C.GstBusFunc(C.cgoBusFunc),
			(C.gpointer)(unsafe.Pointer(fPtr)),
		)),
	)
}
```
The "fPtr" pointer looks leaking and gopointer.Unref() call is absent from RemoveWatch():
```
func (b *Bus) RemoveWatch() bool {
	return gobool(C.gst_bus_remove_watch(b.Instance()))
}
```

### PR DESCRIPTION
**Pull request by RSWilli**
fixes #107 

Analogous to the rust bindings: https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/blob/main/gstreamer/src/bus.rs#L141-160

use [`gst_bus_add_watch_full`](https://gstreamer.freedesktop.org/documentation/gstreamer/gstbus.html?gi-language=c#gst_bus_add_watch_full) to be able to attach a notify function for the cleanup.

### CODE REVIEW

**Comment by nickeygit** [comment]
Yep, this fixes the gopointer leaking!

Thanks!

File: gst/gst_bus.go [hunk 1]
```diff
@@ -300,7 +308,7 @@ func (b *Bus) SetSyncHandler(f BusSyncHandler) {
 		b.Instance(),
 		C.GstBusSyncHandler(C.cgoBusSyncHandler),
 		(C.gpointer)(unsafe.Pointer(ptr)),
-		nil,
+		C.GDestroyNotify(C.cgoDestroyBusWatch),
```
Comment (sdroege) [inline gst/gst_bus.go:311]: You probably want to check if there's any other function that takes a `GDestroyNotify` and you're currently passing `nil` there. Almost certainly that has the same bug.

Comment (RSWilli) [reply gst/gst_bus.go:311]: Yeah that's a good idea, although a lot of work I think. I took a note here: #112
